
namespace BluraySharp.Common
{
	public enum BdUOFlag : byte
	{
		PipPgChange = 0x1E,
		Reserved2,
		SecondaryAudioChange,
		SecondaryAudioEnableDisable,
		SecondaryVideoChange,
		SecondaryVideoEnableDisable,
		PgChange,
		PgEnableDisable,
		PopupOff,
		PopupOn,
		AngleChange,
		Reserved1,
		PrimaryAudioChange,
		SelectAndActivate,
		Activate,
		Select,
		MoveRight,
		MoveLeft,
		MoveDown,
		MoveUp,
		Resume,
		Backward,
		Forward,
		Still,
		PauseOff,
		PauseOn,
		Stop,
		PlayFirstplay,
		SkipToPrevPoint,
		SkipToNextPoint,
		TimeSearch,
		ChapterSearch,
		TitleSearch,
		MenuCall,
	}
}
