//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluraySharp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluraySharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Not Seamless 的本地化字符串。
        /// </summary>
        internal static string Enum_BdConnectionCondition_NotSeamless {
            get {
                return ResourceManager.GetString("Enum_BdConnectionCondition_NotSeamless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seamless 的本地化字符串。
        /// </summary>
        internal static string Enum_BdConnectionCondition_Seamless {
            get {
                return ResourceManager.GetString("Enum_BdConnectionCondition_Seamless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seamless Concatenated 的本地化字符串。
        /// </summary>
        internal static string Enum_BdConnectionCondition_SeamlessConcat {
            get {
                return ResourceManager.GetString("Enum_BdConnectionCondition_SeamlessConcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activate Button 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ActivateButton {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ActivateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Angle Number Change 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_AngleChange {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_AngleChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backward Play 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_BackwardPlay {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_BackwardPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chapter Search 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ChapterSearch {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ChapterSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward Play 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ForwardPlay {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ForwardPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Down Selected Button 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_MoveDownSelectedButton {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_MoveDownSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Left Selected Button 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_MoveLeftSelectedButton {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_MoveLeftSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Right Selected Button 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_MoveRightSelectedButton {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_MoveRightSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Up Selected Button 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_MoveUpSelectedButton {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_MoveUpSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause On 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_PauseOn {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_PauseOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pip Pg textST Stream Number Change 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_PipStChange {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_PipStChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Popup Off 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_PopupOff {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_PopupOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Popup On 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_PopupOn {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_PopupOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primary Audio Stream Number Change 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_PrimaryAudioChange {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_PrimaryAudioChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MenuCall (Reserved) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ReservedForMenuCall {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ReservedForMenuCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PauseOff (Reserved) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ReservedForPauseOff {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ReservedForPauseOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pip Pg textST Enable Disable (Reserved) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ReservedForPipStEnableDisable {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ReservedForPipStEnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play Firstplay (Reserved) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ReservedForPlayFirstplay {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ReservedForPlayFirstplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pg textST Stream Number Change (Reserved) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ReservedForStChange {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ReservedForStChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title Search (Reserved) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ReservedForTitleSearch {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ReservedForTitleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_Resume {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secondary Audio Stream Number Change 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SecondaryAudioChange {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SecondaryAudioChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secondary Audio Enable Disable 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SecondaryAudioEnableDisable {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SecondaryAudioEnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secondary Video Stream Number Change 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SecondaryVideoChange {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SecondaryVideoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secondary Video Enable Disable 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SecondaryVideoEnableDisable {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SecondaryVideoEnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Button 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SelectButton {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Button And Activate 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SelectButtonAndActivate {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SelectButtonAndActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip to Next Point 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SkipToNextPoint {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SkipToNextPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip Back to Previous Point 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SkipToPrevPoint {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SkipToPrevPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subtile Change 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_StChange {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_StChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subtitle Enable/Disable 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_StEnableDisable {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_StEnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Still Off 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_StillOff {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_StillOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_Stop {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Search 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_TimeSearch {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_TimeSearch", resourceCulture);
            }
        }
    }
}
