//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluraySharp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluraySharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Stereo+Multi Combo 的本地化字符串。
        /// </summary>
        internal static string Enum_BdAuPresentationType_Combo {
            get {
                return ResourceManager.GetString("Enum_BdAuPresentationType_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dual Mono 的本地化字符串。
        /// </summary>
        internal static string Enum_BdAuPresentationType_DualMono {
            get {
                return ResourceManager.GetString("Enum_BdAuPresentationType_DualMono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mono 的本地化字符串。
        /// </summary>
        internal static string Enum_BdAuPresentationType_Mono {
            get {
                return ResourceManager.GetString("Enum_BdAuPresentationType_Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multi Channel 的本地化字符串。
        /// </summary>
        internal static string Enum_BdAuPresentationType_Multi {
            get {
                return ResourceManager.GetString("Enum_BdAuPresentationType_Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stereo 的本地化字符串。
        /// </summary>
        internal static string Enum_BdAuPresentationType_Stereo {
            get {
                return ResourceManager.GetString("Enum_BdAuPresentationType_Stereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Enum_BdAuPresentationType_Unknown {
            get {
                return ResourceManager.GetString("Enum_BdAuPresentationType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192 kHz 的本地化字符串。
        /// </summary>
        internal static string Enum_BdAuSampleRate_Au192 {
            get {
                return ResourceManager.GetString("Enum_BdAuSampleRate_Au192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 48 kHz 的本地化字符串。
        /// </summary>
        internal static string Enum_BdAuSampleRate_Au48 {
            get {
                return ResourceManager.GetString("Enum_BdAuSampleRate_Au48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 48+192 kHz Combo 的本地化字符串。
        /// </summary>
        internal static string Enum_BdAuSampleRate_Au48_192 {
            get {
                return ResourceManager.GetString("Enum_BdAuSampleRate_Au48_192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 48+96 kHz Combo 的本地化字符串。
        /// </summary>
        internal static string Enum_BdAuSampleRate_Au48_96 {
            get {
                return ResourceManager.GetString("Enum_BdAuSampleRate_Au48_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 96 kHz 的本地化字符串。
        /// </summary>
        internal static string Enum_BdAuSampleRate_Au96 {
            get {
                return ResourceManager.GetString("Enum_BdAuSampleRate_Au96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Enum_BdAuSampleRate_Unknown {
            get {
                return ResourceManager.GetString("Enum_BdAuSampleRate_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Enum_BdCharacterCodingType_Unknown {
            get {
                return ResourceManager.GetString("Enum_BdCharacterCodingType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTF-16 Big Ending 的本地化字符串。
        /// </summary>
        internal static string Enum_BdCharacterCodingType_UTF16BE {
            get {
                return ResourceManager.GetString("Enum_BdCharacterCodingType_UTF16BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTF-8 的本地化字符串。
        /// </summary>
        internal static string Enum_BdCharacterCodingType_UTF8 {
            get {
                return ResourceManager.GetString("Enum_BdCharacterCodingType_UTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Seamless 的本地化字符串。
        /// </summary>
        internal static string Enum_BdConnectionCondition_NotSeamless {
            get {
                return ResourceManager.GetString("Enum_BdConnectionCondition_NotSeamless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seamless 的本地化字符串。
        /// </summary>
        internal static string Enum_BdConnectionCondition_Seamless {
            get {
                return ResourceManager.GetString("Enum_BdConnectionCondition_Seamless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seamless Concatenated 的本地化字符串。
        /// </summary>
        internal static string Enum_BdConnectionCondition_SeamlessConcat {
            get {
                return ResourceManager.GetString("Enum_BdConnectionCondition_SeamlessConcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Enum_BdConnectionCondition_Unknown {
            get {
                return ResourceManager.GetString("Enum_BdConnectionCondition_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dolby Digital (AC3) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_AuDolby {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_AuDolby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dolby Lossless (TrueHD) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_AuDolbyLossless {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_AuDolbyLossless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dolby Digital Plus (AC3+) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_AuDolbyPlus {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_AuDolbyPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DTS 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_AuDts {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_AuDts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DTS-HD High Resolution Audio (HDHR) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_AuDtsHDHR {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_AuDtsHDHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DTS-HD Master Audio (HDMA) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_AuDtsHDMA {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_AuDtsHDMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linear PCM (LPCM) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_AuLPCM {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_AuLPCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPEG-1 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_AuMpeg1 {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_AuMpeg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPEG-2 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_AuMpeg2 {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_AuMpeg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interractive Graphics (IG) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_GxInterractive {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_GxInterractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Presentation Graphics (PG) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_GxPresentation {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_GxPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dolby Digital Plus (AC3+) for Secodary 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_SaDolbyPlus {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_SaDolbyPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DTS-HD LBR for Secondary 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_SaDtsHD {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_SaDtsHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Subtitle (textST) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_TxSubtitle {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_TxSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_Unknown {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPEG-4 AVC (H.264) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_ViAvc {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_ViAvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPEG-1 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_ViMpeg1 {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_ViMpeg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPEG-2 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_ViMpeg2 {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_ViMpeg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MVC 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_ViMvc {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_ViMvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VC-1 的本地化字符串。
        /// </summary>
        internal static string Enum_BdStreamCodingType_ViVc1 {
            get {
                return ResourceManager.GetString("Enum_BdStreamCodingType_ViVc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activate Button 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ActivateButton {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ActivateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Angle Number Change 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_AngleChange {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_AngleChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backward Play 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_BackwardPlay {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_BackwardPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chapter Search 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ChapterSearch {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ChapterSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward Play 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ForwardPlay {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ForwardPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Down Selected Button 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_MoveDownSelectedButton {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_MoveDownSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Left Selected Button 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_MoveLeftSelectedButton {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_MoveLeftSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Right Selected Button 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_MoveRightSelectedButton {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_MoveRightSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Up Selected Button 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_MoveUpSelectedButton {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_MoveUpSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause On 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_PauseOn {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_PauseOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PiP Pg textST Stream Number Change 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_PipStChange {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_PipStChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Popup Off 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_PopupOff {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_PopupOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Popup On 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_PopupOn {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_PopupOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primary Audio Stream Number Change 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_PrimaryAudioChange {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_PrimaryAudioChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MenuCall (Reserved) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ReservedForMenuCall {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ReservedForMenuCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PauseOff (Reserved) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ReservedForPauseOff {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ReservedForPauseOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PiP Pg textST Enable Disable (Reserved) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ReservedForPipStEnableDisable {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ReservedForPipStEnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play Firstplay (Reserved) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ReservedForPlayFirstplay {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ReservedForPlayFirstplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pg textST Stream Number Change (Reserved) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ReservedForStChange {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ReservedForStChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title Search (Reserved) 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_ReservedForTitleSearch {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_ReservedForTitleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_Resume {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secondary Audio Stream Number Change 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SecondaryAudioChange {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SecondaryAudioChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secondary Audio Enable Disable 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SecondaryAudioEnableDisable {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SecondaryAudioEnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secondary Video Stream Number Change 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SecondaryVideoChange {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SecondaryVideoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secondary Video Enable Disable 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SecondaryVideoEnableDisable {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SecondaryVideoEnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Button 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SelectButton {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Button And Activate 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SelectButtonAndActivate {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SelectButtonAndActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip to Next Point 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SkipToNextPoint {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SkipToNextPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip Back to Previous Point 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_SkipToPrevPoint {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_SkipToPrevPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subtile Change 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_StChange {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_StChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subtitle Enable Disable 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_StEnableDisable {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_StEnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Still Off 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_StillOff {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_StillOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_Stop {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Search 的本地化字符串。
        /// </summary>
        internal static string Enum_BdUOFlag_TimeSearch {
            get {
                return ResourceManager.GetString("Enum_BdUOFlag_TimeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 16:9 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViAspectRatio_Vi16to9 {
            get {
                return ResourceManager.GetString("Enum_BdViAspectRatio_Vi16to9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4:3 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViAspectRatio_Vi4to3 {
            get {
                return ResourceManager.GetString("Enum_BdViAspectRatio_Vi4to3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFormat_Unknown {
            get {
                return ResourceManager.GetString("Enum_BdViFormat_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1080i 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFormat_Vi1080i {
            get {
                return ResourceManager.GetString("Enum_BdViFormat_Vi1080i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1080p 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFormat_Vi1080p {
            get {
                return ResourceManager.GetString("Enum_BdViFormat_Vi1080p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 480i 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFormat_Vi480i {
            get {
                return ResourceManager.GetString("Enum_BdViFormat_Vi480i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 480p 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFormat_Vi480p {
            get {
                return ResourceManager.GetString("Enum_BdViFormat_Vi480p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 576i 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFormat_Vi576i {
            get {
                return ResourceManager.GetString("Enum_BdViFormat_Vi576i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 576p 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFormat_Vi576p {
            get {
                return ResourceManager.GetString("Enum_BdViFormat_Vi576p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 720p 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFormat_Vi720p {
            get {
                return ResourceManager.GetString("Enum_BdViFormat_Vi720p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFrameRate_Unknown {
            get {
                return ResourceManager.GetString("Enum_BdViFrameRate_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 23.976 fps 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFrameRate_Vi23 {
            get {
                return ResourceManager.GetString("Enum_BdViFrameRate_Vi23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 24 fps 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFrameRate_Vi24 {
            get {
                return ResourceManager.GetString("Enum_BdViFrameRate_Vi24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 25 fps 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFrameRate_Vi25 {
            get {
                return ResourceManager.GetString("Enum_BdViFrameRate_Vi25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 29.97 fps 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFrameRate_Vi29 {
            get {
                return ResourceManager.GetString("Enum_BdViFrameRate_Vi29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 50 fps 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFrameRate_Vi50 {
            get {
                return ResourceManager.GetString("Enum_BdViFrameRate_Vi50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 59.94 fps 的本地化字符串。
        /// </summary>
        internal static string Enum_BdViFrameRate_Vi59 {
            get {
                return ResourceManager.GetString("Enum_BdViFrameRate_Vi59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random 的本地化字符串。
        /// </summary>
        internal static string Enum_PlPlaybackType_Random {
            get {
                return ResourceManager.GetString("Enum_PlPlaybackType_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequential 的本地化字符串。
        /// </summary>
        internal static string Enum_PlPlaybackType_Sequential {
            get {
                return ResourceManager.GetString("Enum_PlPlaybackType_Sequential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shuffle 的本地化字符串。
        /// </summary>
        internal static string Enum_PlPlaybackType_Shuffle {
            get {
                return ResourceManager.GetString("Enum_PlPlaybackType_Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Enum_PlPlaybackType_Unknown {
            get {
                return ResourceManager.GetString("Enum_PlPlaybackType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entry Mark 的本地化字符串。
        /// </summary>
        internal static string Enum_PlPlayMarkType_PmEntryMark {
            get {
                return ResourceManager.GetString("Enum_PlPlayMarkType_PmEntryMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link Point 的本地化字符串。
        /// </summary>
        internal static string Enum_PlPlayMarkType_PmLinkPoint {
            get {
                return ResourceManager.GetString("Enum_PlPlayMarkType_PmLinkPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Enum_PlPlayMarkType_Unknown {
            get {
                return ResourceManager.GetString("Enum_PlPlayMarkType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Still 的本地化字符串。
        /// </summary>
        internal static string Enum_PlStillMode_NotStill {
            get {
                return ResourceManager.GetString("Enum_PlStillMode_NotStill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Still for Duration 的本地化字符串。
        /// </summary>
        internal static string Enum_PlStillMode_StillForDuration {
            get {
                return ResourceManager.GetString("Enum_PlStillMode_StillForDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Still Infinitely 的本地化字符串。
        /// </summary>
        internal static string Enum_PlStillMode_StillInfinitely {
            get {
                return ResourceManager.GetString("Enum_PlStillMode_StillInfinitely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In-Mux PiP Stream from a Play Item 的本地化字符串。
        /// </summary>
        internal static string Enum_PlStnEntryType_InMuxPip {
            get {
                return ResourceManager.GetString("Enum_PlStnEntryType_InMuxPip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream from a Play Item 的本地化字符串。
        /// </summary>
        internal static string Enum_PlStnEntryType_PlayItem {
            get {
                return ResourceManager.GetString("Enum_PlStnEntryType_PlayItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream from a Sub Play Item 的本地化字符串。
        /// </summary>
        internal static string Enum_PlStnEntryType_SubPlayItem {
            get {
                return ResourceManager.GetString("Enum_PlStnEntryType_SubPlayItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Enum_PlStnEntryType_Unknown {
            get {
                return ResourceManager.GetString("Enum_PlStnEntryType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interractive Graphics Menu 的本地化字符串。
        /// </summary>
        internal static string Enum_PlSubPathType_IgMenu {
            get {
                return ResourceManager.GetString("Enum_PlSubPathType_IgMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In-Mux Synchronous PiP 的本地化字符串。
        /// </summary>
        internal static string Enum_PlSubPathType_IMSync {
            get {
                return ResourceManager.GetString("Enum_PlSubPathType_IMSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out-of-Mux Asynchronous PiP 的本地化字符串。
        /// </summary>
        internal static string Enum_PlSubPathType_OoMAsync {
            get {
                return ResourceManager.GetString("Enum_PlSubPathType_OoMAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out-of-Mux Synchronous Streams 的本地化字符串。
        /// </summary>
        internal static string Enum_PlSubPathType_OoMSync {
            get {
                return ResourceManager.GetString("Enum_PlSubPathType_OoMSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primary Audio for Browsable Slideshow 的本地化字符串。
        /// </summary>
        internal static string Enum_PlSubPathType_PrAudio {
            get {
                return ResourceManager.GetString("Enum_PlSubPathType_PrAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Textual Subtitle 的本地化字符串。
        /// </summary>
        internal static string Enum_PlSubPathType_TextSub {
            get {
                return ResourceManager.GetString("Enum_PlSubPathType_TextSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Enum_PlSubPathType_Unknown {
            get {
                return ResourceManager.GetString("Enum_PlSubPathType_Unknown", resourceCulture);
            }
        }
    }
}
