using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BluraySharp
{
	public enum BdLang
	{
		LANG_AAR,
		LANG_ABK,
		LANG_ACE,
		LANG_ACH,
		LANG_ADA,
		LANG_ADY,
		LANG_AFA,
		LANG_AFH,
		LANG_AFR,
		LANG_AIN,
		LANG_AKA,
		LANG_AKK,
		LANG_ALB,
		LANG_ALE,
		LANG_ALG,
		LANG_ALT,
		LANG_AMH,
		LANG_ANG,
		LANG_ANP,
		LANG_APA,
		LANG_ARA,
		LANG_ARC,
		LANG_ARG,
		LANG_ARM,
		LANG_ARN,
		LANG_ARP,
		LANG_ART,
		LANG_ARW,
		LANG_ASM,
		LANG_AST,
		LANG_ATH,
		LANG_AUS,
		LANG_AVA,
		LANG_AVE,
		LANG_AWA,
		LANG_AYM,
		LANG_AZE,
		LANG_BAD,
		LANG_BAI,
		LANG_BAK,
		LANG_BAL,
		LANG_BAM,
		LANG_BAN,
		LANG_BAQ,
		LANG_BAS,
		LANG_BAT,
		LANG_BEJ,
		LANG_BEL,
		LANG_BEM,
		LANG_BEN,
		LANG_BER,
		LANG_BHO,
		LANG_BIH,
		LANG_BIK,
		LANG_BIN,
		LANG_BIS,
		LANG_BLA,
		LANG_BNT,
		LANG_BOD,
		LANG_BOS,
		LANG_BRA,
		LANG_BRE,
		LANG_BTK,
		LANG_BUA,
		LANG_BUG,
		LANG_BUL,
		LANG_BUR,
		LANG_BYN,
		LANG_CAD,
		LANG_CAI,
		LANG_CAR,
		LANG_CAT,
		LANG_CAU,
		LANG_CEB,
		LANG_CEL,
		LANG_CES,
		LANG_CHA,
		LANG_CHB,
		LANG_CHE,
		LANG_CHG,
		LANG_CHI,
		LANG_CHK,
		LANG_CHM,
		LANG_CHN,
		LANG_CHO,
		LANG_CHP,
		LANG_CHR,
		LANG_CHU,
		LANG_CHV,
		LANG_CHY,
		LANG_CMC,
		LANG_COP,
		LANG_COR,
		LANG_COS,
		LANG_CPE,
		LANG_CPF,
		LANG_CPP,
		LANG_CRE,
		LANG_CRH,
		LANG_CRP,
		LANG_CSB,
		LANG_CUS,
		LANG_CYM,
		LANG_CZE,
		LANG_DAK,
		LANG_DAN,
		LANG_DAR,
		LANG_DAY,
		LANG_DEL,
		LANG_DEN,
		LANG_DEU,
		LANG_DGR,
		LANG_DIN,
		LANG_DIV,
		LANG_DOI,
		LANG_DRA,
		LANG_DSB,
		LANG_DUA,
		LANG_DUM,
		LANG_DUT,
		LANG_DYU,
		LANG_DZO,
		LANG_EFI,
		LANG_EGY,
		LANG_EKA,
		LANG_ELL,
		LANG_ELX,
		LANG_ENG,
		LANG_ENM,
		LANG_EPO,
		LANG_EST,
		LANG_EUS,
		LANG_EWE,
		LANG_EWO,
		LANG_FAN,
		LANG_FAO,
		LANG_FAS,
		LANG_FAT,
		LANG_FIJ,
		LANG_FIL,
		LANG_FIN,
		LANG_FIU,
		LANG_FON,
		LANG_FRA,
		LANG_FRE,
		LANG_FRM,
		LANG_FRO,
		LANG_FRR,
		LANG_FRS,
		LANG_FRY,
		LANG_FUL,
		LANG_FUR,
		LANG_GAA,
		LANG_GAY,
		LANG_GBA,
		LANG_GEM,
		LANG_GEO,
		LANG_GER,
		LANG_GEZ,
		LANG_GIL,
		LANG_GLA,
		LANG_GLE,
		LANG_GLG,
		LANG_GLV,
		LANG_GMH,
		LANG_GOH,
		LANG_GON,
		LANG_GOR,
		LANG_GOT,
		LANG_GRB,
		LANG_GRC,
		LANG_GRE,
		LANG_GRN,
		LANG_GSW,
		LANG_GUJ,
		LANG_GWI,
		LANG_HAI,
		LANG_HAT,
		LANG_HAU,
		LANG_HAW,
		LANG_HEB,
		LANG_HER,
		LANG_HIL,
		LANG_HIM,
		LANG_HIN,
		LANG_HIT,
		LANG_HMN,
		LANG_HMO,
		LANG_HRV,
		LANG_HSB,
		LANG_HUN,
		LANG_HUP,
		LANG_HYE,
		LANG_IBA,
		LANG_IBO,
		LANG_ICE,
		LANG_IDO,
		LANG_III,
		LANG_IJO,
		LANG_IKU,
		LANG_ILE,
		LANG_ILO,
		LANG_INA,
		LANG_INC,
		LANG_IND,
		LANG_INE,
		LANG_INH,
		LANG_IPK,
		LANG_IRA,
		LANG_IRO,
		LANG_ISL,
		LANG_ITA,
		LANG_JAV,
		LANG_JBO,
		LANG_JPN,
		LANG_JPR,
		LANG_JRB,
		LANG_KAA,
		LANG_KAB,
		LANG_KAC,
		LANG_KAL,
		LANG_KAM,
		LANG_KAN,
		LANG_KAR,
		LANG_KAS,
		LANG_KAT,
		LANG_KAU,
		LANG_KAW,
		LANG_KAZ,
		LANG_KBD,
		LANG_KHA,
		LANG_KHI,
		LANG_KHM,
		LANG_KHO,
		LANG_KIK,
		LANG_KIN,
		LANG_KIR,
		LANG_KMB,
		LANG_KOK,
		LANG_KOM,
		LANG_KON,
		LANG_KOR,
		LANG_KOS,
		LANG_KPE,
		LANG_KRC,
		LANG_KRL,
		LANG_KRO,
		LANG_KRU,
		LANG_KUA,
		LANG_KUM,
		LANG_KUR,
		LANG_KUT,
		LANG_LAD,
		LANG_LAH,
		LANG_LAM,
		LANG_LAO,
		LANG_LAT,
		LANG_LAV,
		LANG_LEZ,
		LANG_LIM,
		LANG_LIN,
		LANG_LIT,
		LANG_LOL,
		LANG_LOZ,
		LANG_LTZ,
		LANG_LUA,
		LANG_LUB,
		LANG_LUG,
		LANG_LUI,
		LANG_LUN,
		LANG_LUO,
		LANG_LUS,
		LANG_MAC,
		LANG_MAD,
		LANG_MAG,
		LANG_MAH,
		LANG_MAI,
		LANG_MAK,
		LANG_MAL,
		LANG_MAN,
		LANG_MAO,
		LANG_MAP,
		LANG_MAR,
		LANG_MAS,
		LANG_MAY,
		LANG_MDF,
		LANG_MDR,
		LANG_MEN,
		LANG_MGA,
		LANG_MIC,
		LANG_MIN,
		LANG_MIS,
		LANG_MKD,
		LANG_MKH,
		LANG_MLG,
		LANG_MLT,
		LANG_MNC,
		LANG_MNI,
		LANG_MNO,
		LANG_MOH,
		LANG_MON,
		LANG_MOS,
		LANG_MRI,
		LANG_MSA,
		LANG_MUL,
		LANG_MUN,
		LANG_MUS,
		LANG_MWL,
		LANG_MWR,
		LANG_MYA,
		LANG_MYN,
		LANG_MYV,
		LANG_NAH,
		LANG_NAI,
		LANG_NAP,
		LANG_NAU,
		LANG_NAV,
		LANG_NBL,
		LANG_NDE,
		LANG_NDO,
		LANG_NDS,
		LANG_NEP,
		LANG_NEW,
		LANG_NIA,
		LANG_NIC,
		LANG_NIU,
		LANG_NLD,
		LANG_NNO,
		LANG_NOB,
		LANG_NOG,
		LANG_NON,
		LANG_NOR,
		LANG_NQO,
		LANG_NSO,
		LANG_NUB,
		LANG_NWC,
		LANG_NYA,
		LANG_NYM,
		LANG_NYN,
		LANG_NYO,
		LANG_NZI,
		LANG_OCI,
		LANG_OJI,
		LANG_ORI,
		LANG_ORM,
		LANG_OSA,
		LANG_OSS,
		LANG_OTA,
		LANG_OTO,
		LANG_PAA,
		LANG_PAG,
		LANG_PAL,
		LANG_PAM,
		LANG_PAN,
		LANG_PAP,
		LANG_PAU,
		LANG_PEO,
		LANG_PER,
		LANG_PHI,
		LANG_PHN,
		LANG_PLI,
		LANG_POL,
		LANG_PON,
		LANG_POR,
		LANG_PRA,
		LANG_PRO,
		LANG_PUS,
		LANG_QAA,
		LANG_QUE,
		LANG_RAJ,
		LANG_RAP,
		LANG_RAR,
		LANG_ROA,
		LANG_ROH,
		LANG_ROM,
		LANG_RON,
		LANG_RUM,
		LANG_RUN,
		LANG_RUP,
		LANG_RUS,
		LANG_SAD,
		LANG_SAG,
		LANG_SAH,
		LANG_SAI,
		LANG_SAL,
		LANG_SAM,
		LANG_SAN,
		LANG_SAS,
		LANG_SAT,
		LANG_SCN,
		LANG_SCO,
		LANG_SEL,
		LANG_SEM,
		LANG_SGA,
		LANG_SGN,
		LANG_SHN,
		LANG_SID,
		LANG_SIN,
		LANG_SIO,
		LANG_SIT,
		LANG_SLA,
		LANG_SLK,
		LANG_SLO,
		LANG_SLV,
		LANG_SMA,
		LANG_SME,
		LANG_SMI,
		LANG_SMJ,
		LANG_SMN,
		LANG_SMO,
		LANG_SMS,
		LANG_SNA,
		LANG_SND,
		LANG_SNK,
		LANG_SOG,
		LANG_SOM,
		LANG_SON,
		LANG_SOT,
		LANG_SPA,
		LANG_SQI,
		LANG_SRD,
		LANG_SRN,
		LANG_SRP,
		LANG_SRR,
		LANG_SSA,
		LANG_SSW,
		LANG_SUK,
		LANG_SUN,
		LANG_SUS,
		LANG_SUX,
		LANG_SWA,
		LANG_SWE,
		LANG_SYC,
		LANG_SYR,
		LANG_TAH,
		LANG_TAI,
		LANG_TAM,
		LANG_TAT,
		LANG_TEL,
		LANG_TEM,
		LANG_TER,
		LANG_TET,
		LANG_TGK,
		LANG_TGL,
		LANG_THA,
		LANG_TIB,
		LANG_TIG,
		LANG_TIR,
		LANG_TIV,
		LANG_TKL,
		LANG_TLH,
		LANG_TLI,
		LANG_TMH,
		LANG_TOG,
		LANG_TON,
		LANG_TPI,
		LANG_TSI,
		LANG_TSN,
		LANG_TSO,
		LANG_TUK,
		LANG_TUM,
		LANG_TUP,
		LANG_TUR,
		LANG_TUT,
		LANG_TVL,
		LANG_TWI,
		LANG_TYV,
		LANG_UDM,
		LANG_UGA,
		LANG_UIG,
		LANG_UKR,
		LANG_UMB,
		LANG_UND,
		LANG_URD,
		LANG_UZB,
		LANG_VAI,
		LANG_VEN,
		LANG_VIE,
		LANG_VOL,
		LANG_VOT,
		LANG_WAK,
		LANG_WAL,
		LANG_WAR,
		LANG_WAS,
		LANG_WEL,
		LANG_WEN,
		LANG_WLN,
		LANG_WOL,
		LANG_XAL,
		LANG_XHO,
		LANG_YAO,
		LANG_YAP,
		LANG_YID,
		LANG_YOR,
		LANG_YPK,
		LANG_ZAP,
		LANG_ZBL,
		LANG_ZEN,
		LANG_ZGH,
		LANG_ZHA,
		LANG_ZHO,
		LANG_ZND,
		LANG_ZUL,
		LANG_ZUN,
		LANG_ZXX,
		LANG_ZZA
	}

	public static class BdLangCode
	{
		private static string CodeOf(BdLang enumValue)
		{
			return BdLangCode.codeTable[enumValue];
		}

		private static BdLang ValueOf(string code)
		{
			string tCode = code.ToLower(System.Globalization.CultureInfo.InvariantCulture);
			return BdLangCode.codeTable.First(x => x.Value.Equals(tCode)).Key;
		}

		private static readonly Dictionary<BdLang, string> codeTable =
			new Dictionary<BdLang, string>()
			{
				{BdLang.LANG_AAR, "aar"},
				{BdLang.LANG_ABK, "abk"},
				{BdLang.LANG_ACE, "ace"},
				{BdLang.LANG_ACH, "ach"},
				{BdLang.LANG_ADA, "ada"},
				{BdLang.LANG_ADY, "ady"},
				{BdLang.LANG_AFA, "afa"},
				{BdLang.LANG_AFH, "afh"},
				{BdLang.LANG_AFR, "afr"},
				{BdLang.LANG_AIN, "ain"},
				{BdLang.LANG_AKA, "aka"},
				{BdLang.LANG_AKK, "akk"},
				{BdLang.LANG_ALB, "alb"},
				{BdLang.LANG_ALE, "ale"},
				{BdLang.LANG_ALG, "alg"},
				{BdLang.LANG_ALT, "alt"},
				{BdLang.LANG_AMH, "amh"},
				{BdLang.LANG_ANG, "ang"},
				{BdLang.LANG_ANP, "anp"},
				{BdLang.LANG_APA, "apa"},
				{BdLang.LANG_ARA, "ara"},
				{BdLang.LANG_ARC, "arc"},
				{BdLang.LANG_ARG, "arg"},
				{BdLang.LANG_ARM, "arm"},
				{BdLang.LANG_ARN, "arn"},
				{BdLang.LANG_ARP, "arp"},
				{BdLang.LANG_ART, "art"},
				{BdLang.LANG_ARW, "arw"},
				{BdLang.LANG_ASM, "asm"},
				{BdLang.LANG_AST, "ast"},
				{BdLang.LANG_ATH, "ath"},
				{BdLang.LANG_AUS, "aus"},
				{BdLang.LANG_AVA, "ava"},
				{BdLang.LANG_AVE, "ave"},
				{BdLang.LANG_AWA, "awa"},
				{BdLang.LANG_AYM, "aym"},
				{BdLang.LANG_AZE, "aze"},
				{BdLang.LANG_BAD, "bad"},
				{BdLang.LANG_BAI, "bai"},
				{BdLang.LANG_BAK, "bak"},
				{BdLang.LANG_BAL, "bal"},
				{BdLang.LANG_BAM, "bam"},
				{BdLang.LANG_BAN, "ban"},
				{BdLang.LANG_BAQ, "baq"},
				{BdLang.LANG_BAS, "bas"},
				{BdLang.LANG_BAT, "bat"},
				{BdLang.LANG_BEJ, "bej"},
				{BdLang.LANG_BEL, "bel"},
				{BdLang.LANG_BEM, "bem"},
				{BdLang.LANG_BEN, "ben"},
				{BdLang.LANG_BER, "ber"},
				{BdLang.LANG_BHO, "bho"},
				{BdLang.LANG_BIH, "bih"},
				{BdLang.LANG_BIK, "bik"},
				{BdLang.LANG_BIN, "bin"},
				{BdLang.LANG_BIS, "bis"},
				{BdLang.LANG_BLA, "bla"},
				{BdLang.LANG_BNT, "bnt"},
				{BdLang.LANG_BOD, "bod"},
				{BdLang.LANG_BOS, "bos"},
				{BdLang.LANG_BRA, "bra"},
				{BdLang.LANG_BRE, "bre"},
				{BdLang.LANG_BTK, "btk"},
				{BdLang.LANG_BUA, "bua"},
				{BdLang.LANG_BUG, "bug"},
				{BdLang.LANG_BUL, "bul"},
				{BdLang.LANG_BUR, "bur"},
				{BdLang.LANG_BYN, "byn"},
				{BdLang.LANG_CAD, "cad"},
				{BdLang.LANG_CAI, "cai"},
				{BdLang.LANG_CAR, "car"},
				{BdLang.LANG_CAT, "cat"},
				{BdLang.LANG_CAU, "cau"},
				{BdLang.LANG_CEB, "ceb"},
				{BdLang.LANG_CEL, "cel"},
				{BdLang.LANG_CES, "ces"},
				{BdLang.LANG_CHA, "cha"},
				{BdLang.LANG_CHB, "chb"},
				{BdLang.LANG_CHE, "che"},
				{BdLang.LANG_CHG, "chg"},
				{BdLang.LANG_CHI, "chi"},
				{BdLang.LANG_CHK, "chk"},
				{BdLang.LANG_CHM, "chm"},
				{BdLang.LANG_CHN, "chn"},
				{BdLang.LANG_CHO, "cho"},
				{BdLang.LANG_CHP, "chp"},
				{BdLang.LANG_CHR, "chr"},
				{BdLang.LANG_CHU, "chu"},
				{BdLang.LANG_CHV, "chv"},
				{BdLang.LANG_CHY, "chy"},
				{BdLang.LANG_CMC, "cmc"},
				{BdLang.LANG_COP, "cop"},
				{BdLang.LANG_COR, "cor"},
				{BdLang.LANG_COS, "cos"},
				{BdLang.LANG_CPE, "cpe"},
				{BdLang.LANG_CPF, "cpf"},
				{BdLang.LANG_CPP, "cpp"},
				{BdLang.LANG_CRE, "cre"},
				{BdLang.LANG_CRH, "crh"},
				{BdLang.LANG_CRP, "crp"},
				{BdLang.LANG_CSB, "csb"},
				{BdLang.LANG_CUS, "cus"},
				{BdLang.LANG_CYM, "cym"},
				{BdLang.LANG_CZE, "cze"},
				{BdLang.LANG_DAK, "dak"},
				{BdLang.LANG_DAN, "dan"},
				{BdLang.LANG_DAR, "dar"},
				{BdLang.LANG_DAY, "day"},
				{BdLang.LANG_DEL, "del"},
				{BdLang.LANG_DEN, "den"},
				{BdLang.LANG_DEU, "deu"},
				{BdLang.LANG_DGR, "dgr"},
				{BdLang.LANG_DIN, "din"},
				{BdLang.LANG_DIV, "div"},
				{BdLang.LANG_DOI, "doi"},
				{BdLang.LANG_DRA, "dra"},
				{BdLang.LANG_DSB, "dsb"},
				{BdLang.LANG_DUA, "dua"},
				{BdLang.LANG_DUM, "dum"},
				{BdLang.LANG_DUT, "dut"},
				{BdLang.LANG_DYU, "dyu"},
				{BdLang.LANG_DZO, "dzo"},
				{BdLang.LANG_EFI, "efi"},
				{BdLang.LANG_EGY, "egy"},
				{BdLang.LANG_EKA, "eka"},
				{BdLang.LANG_ELL, "ell"},
				{BdLang.LANG_ELX, "elx"},
				{BdLang.LANG_ENG, "eng"},
				{BdLang.LANG_ENM, "enm"},
				{BdLang.LANG_EPO, "epo"},
				{BdLang.LANG_EST, "est"},
				{BdLang.LANG_EUS, "eus"},
				{BdLang.LANG_EWE, "ewe"},
				{BdLang.LANG_EWO, "ewo"},
				{BdLang.LANG_FAN, "fan"},
				{BdLang.LANG_FAO, "fao"},
				{BdLang.LANG_FAS, "fas"},
				{BdLang.LANG_FAT, "fat"},
				{BdLang.LANG_FIJ, "fij"},
				{BdLang.LANG_FIL, "fil"},
				{BdLang.LANG_FIN, "fin"},
				{BdLang.LANG_FIU, "fiu"},
				{BdLang.LANG_FON, "fon"},
				{BdLang.LANG_FRA, "fra"},
				{BdLang.LANG_FRE, "fre"},
				{BdLang.LANG_FRM, "frm"},
				{BdLang.LANG_FRO, "fro"},
				{BdLang.LANG_FRR, "frr"},
				{BdLang.LANG_FRS, "frs"},
				{BdLang.LANG_FRY, "fry"},
				{BdLang.LANG_FUL, "ful"},
				{BdLang.LANG_FUR, "fur"},
				{BdLang.LANG_GAA, "gaa"},
				{BdLang.LANG_GAY, "gay"},
				{BdLang.LANG_GBA, "gba"},
				{BdLang.LANG_GEM, "gem"},
				{BdLang.LANG_GEO, "geo"},
				{BdLang.LANG_GER, "ger"},
				{BdLang.LANG_GEZ, "gez"},
				{BdLang.LANG_GIL, "gil"},
				{BdLang.LANG_GLA, "gla"},
				{BdLang.LANG_GLE, "gle"},
				{BdLang.LANG_GLG, "glg"},
				{BdLang.LANG_GLV, "glv"},
				{BdLang.LANG_GMH, "gmh"},
				{BdLang.LANG_GOH, "goh"},
				{BdLang.LANG_GON, "gon"},
				{BdLang.LANG_GOR, "gor"},
				{BdLang.LANG_GOT, "got"},
				{BdLang.LANG_GRB, "grb"},
				{BdLang.LANG_GRC, "grc"},
				{BdLang.LANG_GRE, "gre"},
				{BdLang.LANG_GRN, "grn"},
				{BdLang.LANG_GSW, "gsw"},
				{BdLang.LANG_GUJ, "guj"},
				{BdLang.LANG_GWI, "gwi"},
				{BdLang.LANG_HAI, "hai"},
				{BdLang.LANG_HAT, "hat"},
				{BdLang.LANG_HAU, "hau"},
				{BdLang.LANG_HAW, "haw"},
				{BdLang.LANG_HEB, "heb"},
				{BdLang.LANG_HER, "her"},
				{BdLang.LANG_HIL, "hil"},
				{BdLang.LANG_HIM, "him"},
				{BdLang.LANG_HIN, "hin"},
				{BdLang.LANG_HIT, "hit"},
				{BdLang.LANG_HMN, "hmn"},
				{BdLang.LANG_HMO, "hmo"},
				{BdLang.LANG_HRV, "hrv"},
				{BdLang.LANG_HSB, "hsb"},
				{BdLang.LANG_HUN, "hun"},
				{BdLang.LANG_HUP, "hup"},
				{BdLang.LANG_HYE, "hye"},
				{BdLang.LANG_IBA, "iba"},
				{BdLang.LANG_IBO, "ibo"},
				{BdLang.LANG_ICE, "ice"},
				{BdLang.LANG_IDO, "ido"},
				{BdLang.LANG_III, "iii"},
				{BdLang.LANG_IJO, "ijo"},
				{BdLang.LANG_IKU, "iku"},
				{BdLang.LANG_ILE, "ile"},
				{BdLang.LANG_ILO, "ilo"},
				{BdLang.LANG_INA, "ina"},
				{BdLang.LANG_INC, "inc"},
				{BdLang.LANG_IND, "ind"},
				{BdLang.LANG_INE, "ine"},
				{BdLang.LANG_INH, "inh"},
				{BdLang.LANG_IPK, "ipk"},
				{BdLang.LANG_IRA, "ira"},
				{BdLang.LANG_IRO, "iro"},
				{BdLang.LANG_ISL, "isl"},
				{BdLang.LANG_ITA, "ita"},
				{BdLang.LANG_JAV, "jav"},
				{BdLang.LANG_JBO, "jbo"},
				{BdLang.LANG_JPN, "jpn"},
				{BdLang.LANG_JPR, "jpr"},
				{BdLang.LANG_JRB, "jrb"},
				{BdLang.LANG_KAA, "kaa"},
				{BdLang.LANG_KAB, "kab"},
				{BdLang.LANG_KAC, "kac"},
				{BdLang.LANG_KAL, "kal"},
				{BdLang.LANG_KAM, "kam"},
				{BdLang.LANG_KAN, "kan"},
				{BdLang.LANG_KAR, "kar"},
				{BdLang.LANG_KAS, "kas"},
				{BdLang.LANG_KAT, "kat"},
				{BdLang.LANG_KAU, "kau"},
				{BdLang.LANG_KAW, "kaw"},
				{BdLang.LANG_KAZ, "kaz"},
				{BdLang.LANG_KBD, "kbd"},
				{BdLang.LANG_KHA, "kha"},
				{BdLang.LANG_KHI, "khi"},
				{BdLang.LANG_KHM, "khm"},
				{BdLang.LANG_KHO, "kho"},
				{BdLang.LANG_KIK, "kik"},
				{BdLang.LANG_KIN, "kin"},
				{BdLang.LANG_KIR, "kir"},
				{BdLang.LANG_KMB, "kmb"},
				{BdLang.LANG_KOK, "kok"},
				{BdLang.LANG_KOM, "kom"},
				{BdLang.LANG_KON, "kon"},
				{BdLang.LANG_KOR, "kor"},
				{BdLang.LANG_KOS, "kos"},
				{BdLang.LANG_KPE, "kpe"},
				{BdLang.LANG_KRC, "krc"},
				{BdLang.LANG_KRL, "krl"},
				{BdLang.LANG_KRO, "kro"},
				{BdLang.LANG_KRU, "kru"},
				{BdLang.LANG_KUA, "kua"},
				{BdLang.LANG_KUM, "kum"},
				{BdLang.LANG_KUR, "kur"},
				{BdLang.LANG_KUT, "kut"},
				{BdLang.LANG_LAD, "lad"},
				{BdLang.LANG_LAH, "lah"},
				{BdLang.LANG_LAM, "lam"},
				{BdLang.LANG_LAO, "lao"},
				{BdLang.LANG_LAT, "lat"},
				{BdLang.LANG_LAV, "lav"},
				{BdLang.LANG_LEZ, "lez"},
				{BdLang.LANG_LIM, "lim"},
				{BdLang.LANG_LIN, "lin"},
				{BdLang.LANG_LIT, "lit"},
				{BdLang.LANG_LOL, "lol"},
				{BdLang.LANG_LOZ, "loz"},
				{BdLang.LANG_LTZ, "ltz"},
				{BdLang.LANG_LUA, "lua"},
				{BdLang.LANG_LUB, "lub"},
				{BdLang.LANG_LUG, "lug"},
				{BdLang.LANG_LUI, "lui"},
				{BdLang.LANG_LUN, "lun"},
				{BdLang.LANG_LUO, "luo"},
				{BdLang.LANG_LUS, "lus"},
				{BdLang.LANG_MAC, "mac"},
				{BdLang.LANG_MAD, "mad"},
				{BdLang.LANG_MAG, "mag"},
				{BdLang.LANG_MAH, "mah"},
				{BdLang.LANG_MAI, "mai"},
				{BdLang.LANG_MAK, "mak"},
				{BdLang.LANG_MAL, "mal"},
				{BdLang.LANG_MAN, "man"},
				{BdLang.LANG_MAO, "mao"},
				{BdLang.LANG_MAP, "map"},
				{BdLang.LANG_MAR, "mar"},
				{BdLang.LANG_MAS, "mas"},
				{BdLang.LANG_MAY, "may"},
				{BdLang.LANG_MDF, "mdf"},
				{BdLang.LANG_MDR, "mdr"},
				{BdLang.LANG_MEN, "men"},
				{BdLang.LANG_MGA, "mga"},
				{BdLang.LANG_MIC, "mic"},
				{BdLang.LANG_MIN, "min"},
				{BdLang.LANG_MIS, "mis"},
				{BdLang.LANG_MKD, "mkd"},
				{BdLang.LANG_MKH, "mkh"},
				{BdLang.LANG_MLG, "mlg"},
				{BdLang.LANG_MLT, "mlt"},
				{BdLang.LANG_MNC, "mnc"},
				{BdLang.LANG_MNI, "mni"},
				{BdLang.LANG_MNO, "mno"},
				{BdLang.LANG_MOH, "moh"},
				{BdLang.LANG_MON, "mon"},
				{BdLang.LANG_MOS, "mos"},
				{BdLang.LANG_MRI, "mri"},
				{BdLang.LANG_MSA, "msa"},
				{BdLang.LANG_MUL, "mul"},
				{BdLang.LANG_MUN, "mun"},
				{BdLang.LANG_MUS, "mus"},
				{BdLang.LANG_MWL, "mwl"},
				{BdLang.LANG_MWR, "mwr"},
				{BdLang.LANG_MYA, "mya"},
				{BdLang.LANG_MYN, "myn"},
				{BdLang.LANG_MYV, "myv"},
				{BdLang.LANG_NAH, "nah"},
				{BdLang.LANG_NAI, "nai"},
				{BdLang.LANG_NAP, "nap"},
				{BdLang.LANG_NAU, "nau"},
				{BdLang.LANG_NAV, "nav"},
				{BdLang.LANG_NBL, "nbl"},
				{BdLang.LANG_NDE, "nde"},
				{BdLang.LANG_NDO, "ndo"},
				{BdLang.LANG_NDS, "nds"},
				{BdLang.LANG_NEP, "nep"},
				{BdLang.LANG_NEW, "new"},
				{BdLang.LANG_NIA, "nia"},
				{BdLang.LANG_NIC, "nic"},
				{BdLang.LANG_NIU, "niu"},
				{BdLang.LANG_NLD, "nld"},
				{BdLang.LANG_NNO, "nno"},
				{BdLang.LANG_NOB, "nob"},
				{BdLang.LANG_NOG, "nog"},
				{BdLang.LANG_NON, "non"},
				{BdLang.LANG_NOR, "nor"},
				{BdLang.LANG_NQO, "nqo"},
				{BdLang.LANG_NSO, "nso"},
				{BdLang.LANG_NUB, "nub"},
				{BdLang.LANG_NWC, "nwc"},
				{BdLang.LANG_NYA, "nya"},
				{BdLang.LANG_NYM, "nym"},
				{BdLang.LANG_NYN, "nyn"},
				{BdLang.LANG_NYO, "nyo"},
				{BdLang.LANG_NZI, "nzi"},
				{BdLang.LANG_OCI, "oci"},
				{BdLang.LANG_OJI, "oji"},
				{BdLang.LANG_ORI, "ori"},
				{BdLang.LANG_ORM, "orm"},
				{BdLang.LANG_OSA, "osa"},
				{BdLang.LANG_OSS, "oss"},
				{BdLang.LANG_OTA, "ota"},
				{BdLang.LANG_OTO, "oto"},
				{BdLang.LANG_PAA, "paa"},
				{BdLang.LANG_PAG, "pag"},
				{BdLang.LANG_PAL, "pal"},
				{BdLang.LANG_PAM, "pam"},
				{BdLang.LANG_PAN, "pan"},
				{BdLang.LANG_PAP, "pap"},
				{BdLang.LANG_PAU, "pau"},
				{BdLang.LANG_PEO, "peo"},
				{BdLang.LANG_PER, "per"},
				{BdLang.LANG_PHI, "phi"},
				{BdLang.LANG_PHN, "phn"},
				{BdLang.LANG_PLI, "pli"},
				{BdLang.LANG_POL, "pol"},
				{BdLang.LANG_PON, "pon"},
				{BdLang.LANG_POR, "por"},
				{BdLang.LANG_PRA, "pra"},
				{BdLang.LANG_PRO, "pro"},
				{BdLang.LANG_PUS, "pus"},
				{BdLang.LANG_QAA, "qaa"},
				{BdLang.LANG_QUE, "que"},
				{BdLang.LANG_RAJ, "raj"},
				{BdLang.LANG_RAP, "rap"},
				{BdLang.LANG_RAR, "rar"},
				{BdLang.LANG_ROA, "roa"},
				{BdLang.LANG_ROH, "roh"},
				{BdLang.LANG_ROM, "rom"},
				{BdLang.LANG_RON, "ron"},
				{BdLang.LANG_RUM, "rum"},
				{BdLang.LANG_RUN, "run"},
				{BdLang.LANG_RUP, "rup"},
				{BdLang.LANG_RUS, "rus"},
				{BdLang.LANG_SAD, "sad"},
				{BdLang.LANG_SAG, "sag"},
				{BdLang.LANG_SAH, "sah"},
				{BdLang.LANG_SAI, "sai"},
				{BdLang.LANG_SAL, "sal"},
				{BdLang.LANG_SAM, "sam"},
				{BdLang.LANG_SAN, "san"},
				{BdLang.LANG_SAS, "sas"},
				{BdLang.LANG_SAT, "sat"},
				{BdLang.LANG_SCN, "scn"},
				{BdLang.LANG_SCO, "sco"},
				{BdLang.LANG_SEL, "sel"},
				{BdLang.LANG_SEM, "sem"},
				{BdLang.LANG_SGA, "sga"},
				{BdLang.LANG_SGN, "sgn"},
				{BdLang.LANG_SHN, "shn"},
				{BdLang.LANG_SID, "sid"},
				{BdLang.LANG_SIN, "sin"},
				{BdLang.LANG_SIO, "sio"},
				{BdLang.LANG_SIT, "sit"},
				{BdLang.LANG_SLA, "sla"},
				{BdLang.LANG_SLK, "slk"},
				{BdLang.LANG_SLO, "slo"},
				{BdLang.LANG_SLV, "slv"},
				{BdLang.LANG_SMA, "sma"},
				{BdLang.LANG_SME, "sme"},
				{BdLang.LANG_SMI, "smi"},
				{BdLang.LANG_SMJ, "smj"},
				{BdLang.LANG_SMN, "smn"},
				{BdLang.LANG_SMO, "smo"},
				{BdLang.LANG_SMS, "sms"},
				{BdLang.LANG_SNA, "sna"},
				{BdLang.LANG_SND, "snd"},
				{BdLang.LANG_SNK, "snk"},
				{BdLang.LANG_SOG, "sog"},
				{BdLang.LANG_SOM, "som"},
				{BdLang.LANG_SON, "son"},
				{BdLang.LANG_SOT, "sot"},
				{BdLang.LANG_SPA, "spa"},
				{BdLang.LANG_SQI, "sqi"},
				{BdLang.LANG_SRD, "srd"},
				{BdLang.LANG_SRN, "srn"},
				{BdLang.LANG_SRP, "srp"},
				{BdLang.LANG_SRR, "srr"},
				{BdLang.LANG_SSA, "ssa"},
				{BdLang.LANG_SSW, "ssw"},
				{BdLang.LANG_SUK, "suk"},
				{BdLang.LANG_SUN, "sun"},
				{BdLang.LANG_SUS, "sus"},
				{BdLang.LANG_SUX, "sux"},
				{BdLang.LANG_SWA, "swa"},
				{BdLang.LANG_SWE, "swe"},
				{BdLang.LANG_SYC, "syc"},
				{BdLang.LANG_SYR, "syr"},
				{BdLang.LANG_TAH, "tah"},
				{BdLang.LANG_TAI, "tai"},
				{BdLang.LANG_TAM, "tam"},
				{BdLang.LANG_TAT, "tat"},
				{BdLang.LANG_TEL, "tel"},
				{BdLang.LANG_TEM, "tem"},
				{BdLang.LANG_TER, "ter"},
				{BdLang.LANG_TET, "tet"},
				{BdLang.LANG_TGK, "tgk"},
				{BdLang.LANG_TGL, "tgl"},
				{BdLang.LANG_THA, "tha"},
				{BdLang.LANG_TIB, "tib"},
				{BdLang.LANG_TIG, "tig"},
				{BdLang.LANG_TIR, "tir"},
				{BdLang.LANG_TIV, "tiv"},
				{BdLang.LANG_TKL, "tkl"},
				{BdLang.LANG_TLH, "tlh"},
				{BdLang.LANG_TLI, "tli"},
				{BdLang.LANG_TMH, "tmh"},
				{BdLang.LANG_TOG, "tog"},
				{BdLang.LANG_TON, "ton"},
				{BdLang.LANG_TPI, "tpi"},
				{BdLang.LANG_TSI, "tsi"},
				{BdLang.LANG_TSN, "tsn"},
				{BdLang.LANG_TSO, "tso"},
				{BdLang.LANG_TUK, "tuk"},
				{BdLang.LANG_TUM, "tum"},
				{BdLang.LANG_TUP, "tup"},
				{BdLang.LANG_TUR, "tur"},
				{BdLang.LANG_TUT, "tut"},
				{BdLang.LANG_TVL, "tvl"},
				{BdLang.LANG_TWI, "twi"},
				{BdLang.LANG_TYV, "tyv"},
				{BdLang.LANG_UDM, "udm"},
				{BdLang.LANG_UGA, "uga"},
				{BdLang.LANG_UIG, "uig"},
				{BdLang.LANG_UKR, "ukr"},
				{BdLang.LANG_UMB, "umb"},
				{BdLang.LANG_UND, "und"},
				{BdLang.LANG_URD, "urd"},
				{BdLang.LANG_UZB, "uzb"},
				{BdLang.LANG_VAI, "vai"},
				{BdLang.LANG_VEN, "ven"},
				{BdLang.LANG_VIE, "vie"},
				{BdLang.LANG_VOL, "vol"},
				{BdLang.LANG_VOT, "vot"},
				{BdLang.LANG_WAK, "wak"},
				{BdLang.LANG_WAL, "wal"},
				{BdLang.LANG_WAR, "war"},
				{BdLang.LANG_WAS, "was"},
				{BdLang.LANG_WEL, "wel"},
				{BdLang.LANG_WEN, "wen"},
				{BdLang.LANG_WLN, "wln"},
				{BdLang.LANG_WOL, "wol"},
				{BdLang.LANG_XAL, "xal"},
				{BdLang.LANG_XHO, "xho"},
				{BdLang.LANG_YAO, "yao"},
				{BdLang.LANG_YAP, "yap"},
				{BdLang.LANG_YID, "yid"},
				{BdLang.LANG_YOR, "yor"},
				{BdLang.LANG_YPK, "ypk"},
				{BdLang.LANG_ZAP, "zap"},
				{BdLang.LANG_ZBL, "zbl"},
				{BdLang.LANG_ZEN, "zen"},
				{BdLang.LANG_ZGH, "zgh"},
				{BdLang.LANG_ZHA, "zha"},
				{BdLang.LANG_ZHO, "zho"},
				{BdLang.LANG_ZND, "znd"},
				{BdLang.LANG_ZUL, "zul"},
				{BdLang.LANG_ZUN, "zun"},
				{BdLang.LANG_ZXX, "zxx"},
				{BdLang.LANG_ZZA, "zza"}
			};
	}
}
